### ISSUE TITLE
Inconsistency in API Documentation

### ISSUE THREAD

**Issue by ermesonqueiroz** [LibreSign/libresign.github.io#14]
Hello,

I have encountered an inconsistency in the API documentation. The online documentation appears to be outdated and does not match the actual functionality of the API. However, upon running the project locally on my machine, I noticed that the locally generated documentation is correct and up-to-date.

Could you please update the online documentation to match the current state of the API as reflected in the local documentation?

## Example
| online | local |
| ------ | ----- |
| ![image](https://github.com/LibreSign/libresign.github.io/assets/111156073/075f9df6-f91f-4e10-afee-74547b3dffba) | ![image](https://github.com/LibreSign/libresign.github.io/assets/111156073/b57790a6-1f3c-4500-965e-74d0523a91f6) |

**Comment by ermesonqueiroz** [comment]
Observing the actions in this repository I realized that the error is an outdated package. I have already made the necessary changes and am creating a PR containing the changes.

**Comment by vitormattos** [comment]
The API documentation was replaced by json files at root of libresign repository and now you can see the documentation using this app: https://apps.nextcloud.com/apps/ocs_api_viewer

We need to identify a way to put the swagger documentation at libresign.coop site.

**Comment by vitormattos** [comment]
I only didn't stopped this webpage and archived this repository because I need to think about how we will put the documentation at libesign.coop website.
